workflows:
  ios-build:
    name: Build ISign .ipa
    environment:
      xcode: latest
    scripts:
      - name: Build .xcarchive
        script: |
          xcodebuild -project ISign.xcodeproj \
                     -scheme ISign \
                     -configuration Release \
                     -sdk iphoneos \
                     -archivePath $CM_BUILD_DIR/ISign.xcarchive \
                     clean archive
      - name: Export .ipa
        script: |
          xcodebuild -exportArchive \
                     -archivePath $CM_BUILD_DIR/ISign.xcarchive \
                     -exportPath $CM_BUILD_DIR/ExportedIPA \
                     -allowProvisioningUpdates
    artifacts:
      - ExportedIPA/*.ipa
